version: "3"
services:
  # dev:
  #   image: node:12.6
  #   volumes:
  #     - ./:/home/node-web-server/app
  #   working_dir: /home/node-web-server/app
  #   depends_on:
  #     - db
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 5566:5566
  #     - 6677:6677
  #   command: "yarn start"
  redis:
    image: redis:5.0.8-alpine
  rabbitmq:
    image: rabbitmq:3.8.3-alpine
  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/data/db
